version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    expose:
      - "3000"  # Expose port 3000 internally, no need to map it to the host
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=nestjs_demo
    depends_on:
      - mysqldb

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"  # Map port 8080 on host to port 80 inside container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount nginx.conf file
    depends_on:
      - app

  mysqldb:
    image: mysql:8.0
    container_name: nestjs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestjs_demo
    ports:
      - "3307:3306"  # Expose MySQL port 3306 to host port 3307
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
volumes:
  db_data:
